language: groovy

jdk:
  - oraclejdk7
  
before_install:
  - chmod +x gradlew

script:
  - ./gradlew gen

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
